version: "3.9"

services:
  app:
    container_name: jobfetcher
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
      SEND_MESSAGE_TELEGRAM: ${SEND_MESSAGE_TELEGRAM}
    volumes:
      - ./data:/app/data # Monte tout le dossier, pas juste le fichier
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  db:
